'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, Edit3, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import type { VettedOpportunity } from '@/app/api/earn/opportunities/route';

interface Step2Props {
  selectedOpp: VettedOpportunity;
  onApprove: (customPrice: string) => void;
  onChangeMove: () => void;
}

export function Step2Plan({ selectedOpp, onApprove, onChangeMove }: Step2Props) {
  const [plan, setPlan] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [typedText, setTypedText] = useState('');
  const [customPrice, setCustomPrice] = useState('$450');
  const [isEditingPrice, setIsEditingPrice] = useState(false);

  useEffect(() => {
    fetchPlan();
  }, [selectedOpp]);

  const fetchPlan = async () => {
    setLoading(true);
    setTypedText('');
    try {
      const res = await fetch('/api/earn/plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          opportunityTitle: selectedOpp.title,
          category: selectedOpp.category,
          customPrice,
        }),
      });
      const data = await res.json();
      if (data.ok && data.plan) {
        setPlan(data.plan);
        streamPlanText(data.plan.whatIsBeingSold);
      }
    } catch {
      toast.error('Failed to generate plan.');
    } finally {
      setLoading(false);
    }
  };

  const streamPlanText = (fullText: string) => {
    let index = 0;
    const interval = setInterval(() => {
      index += 3;
      setTypedText(fullText.slice(0, index));
      if (index >= fullText.length) {
        clearInterval(interval);
      }
    }, 15);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -15 }}
      className="max-w-3xl mx-auto space-y-6 text-left"
    >
      <div className="text-center mb-6">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#00F0FF]/10 border border-[#00F0FF]/20 text-xs font-mono text-[#00F0FF] mb-2">
          <Sparkles className="w-3.5 h-3.5" /> AI BRAINSTORM CHAMBER
        </div>
        <h2 className="text-2xl md:text-4xl font-extrabold text-white mb-1">
          {selectedOpp.title}
        </h2>
        <p className="text-xs font-mono text-[#8E9BB4]">
          The AI has drafted your full sales and deliverable blueprint. Review and approve below.
        </p>
      </div>

      <div className="rounded-2xl bg-black/60 border border-white/10 p-6 space-y-5 font-mono text-left shadow-[0_10px_40px_rgba(0,0,0,0.8)] backdrop-blur-xl">
        {/* Section 1: What is being sold */}
        <div>
          <span className="text-[10px] text-[#00F0FF] font-bold uppercase tracking-wider block mb-1">
            1. WHAT IS BEING SOLD
          </span>
          <p className="text-xs text-white leading-relaxed">
            {typedText || plan?.whatIsBeingSold || selectedOpp.title}
            <span className="inline-block w-1.5 h-3.5 bg-[#00F0FF] ml-1 animate-pulse" />
          </p>
        </div>

        {/* Section 2: Target Buyer */}
        <div className="pt-3 border-t border-white/[0.06]">
          <span className="text-[10px] text-[#FFD700] font-bold uppercase tracking-wider block mb-1">
            2. WHO BUYS THIS
          </span>
          <p className="text-xs text-[#8E9BB4] leading-relaxed">
            {plan?.targetBuyer || 'Verified business operators with active pain point demand.'}
          </p>
        </div>

        {/* Section 3: Deliverables */}
        <div className="pt-3 border-t border-white/[0.06]">
          <span className="text-[10px] text-[#00FF66] font-bold uppercase tracking-wider block mb-2">
            3. DELIVERABLES GENERATED BY THE SWARM
          </span>
          <div className="space-y-2">
            {(plan?.deliverables || [
              { name: 'Executive Technical Brief & Setup SOP', purpose: 'Handover steps.' },
              { name: 'Turnkey Master Deliverable Asset', purpose: 'Core problem-solving asset.' },
              { name: 'Personalized Cold Pitch Script', purpose: 'High-converting client proposal.' },
            ]).map((del: any) => (
              <div key={del.name} className="p-2.5 rounded bg-white/[0.02] border border-white/[0.04] text-xs">
                <div className="font-bold text-white flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#00FF66]" /> {del.name}
                </div>
                <div className="text-[11px] text-[#8E9BB4] ml-5">{del.purpose}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4: Price & Sales Approach */}
        <div className="pt-3 border-t border-white/[0.06] flex flex-wrap items-center justify-between gap-4">
          <div>
            <span className="text-[10px] text-[#8E9BB4] uppercase block">Target Price Per Sale:</span>
            {isEditingPrice ? (
              <div className="flex items-center gap-2 mt-1">
                <input
                  type="text"
                  value={customPrice}
                  onChange={(e) => setCustomPrice(e.target.value)}
                  className="bg-black/60 border border-white/20 rounded px-2 py-1 text-sm text-white font-mono w-28"
                />
                <Button size="sm" onClick={() => setIsEditingPrice(false)} className="h-7 text-xs">
                  Done
                </Button>
              </div>
            ) : (
              <div className="flex items-center gap-2 mt-1">
                <span className="text-lg font-bold text-[#FFD700]">{customPrice}</span>
                <button
                  onClick={() => setIsEditingPrice(true)}
                  className="text-[10px] text-[#8E9BB4] hover:text-white flex items-center gap-1"
                >
                  <Edit3 className="w-3 h-3" /> Edit Price
                </button>
              </div>
            )}
          </div>

          <div className="text-right">
            <span className="text-[10px] text-[#8E9BB4] uppercase block">Turnkey Delivery Window:</span>
            <span className="text-sm font-bold text-white font-mono">{selectedOpp.timeToDeliver}</span>
          </div>
        </div>

        {/* Compliance note */}
        <div className="p-3 rounded-xl bg-[#00F0FF]/5 border border-[#00F0FF]/20 text-[11px] text-[#00F0FF] flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 shrink-0" />
          <span>Zero automated messaging: All outreach starts in Manual mode for your review.</span>
        </div>
      </div>

      {/* Approval Action */}
      <div className="flex items-center justify-center gap-4 pt-4">
        <Button
          variant="outline"
          onClick={onChangeMove}
          className="border-white/10 text-xs font-mono uppercase h-11 px-5"
        >
          Change Move
        </Button>

        <Button
          size="lg"
          onClick={() => onApprove(customPrice)}
          className="cyan-gradient text-black font-extrabold uppercase px-8 h-12 font-mono shadow-[0_0_25px_rgba(0,240,255,0.4)]"
        >
          <Zap className="w-4 h-4 mr-2 fill-current" /> Approve Plan &amp; Deploy Swarm &rarr;
        </Button>
      </div>
    </motion.div>
  );
}