import fs from 'fs';
import path from 'path';
import { prisma } from '../lib/db';
import { JobStage } from '@prisma/client';
import { invalidateServerCatalogCache } from '../lib/cosmetics/server-catalog';

async function resetSwarmJobs() {
  const isConfirm = process.argv.includes('--confirm');
  console.log('=== FORGE SWARM PHASE 2.5 PIPELINE RESET ===');

  if (!isConfirm) {
    console.log('[DRY RUN] Would mark AssetJob rows as DEAD_LETTER.');
    const jobsCount = await prisma.assetJob.count({ where: { stage: { notIn: [JobStage.DEAD_LETTER] } } });
    console.log(`[DRY RUN] Would mark ${jobsCount} AssetJob rows as DEAD_LETTER.`);

    const cosmeticsCount = await prisma.cosmetic.count({ where: { renderConfig: { not: null as any } } });
    console.log(`[DRY RUN] Would reset ${cosmeticsCount} published Cosmetic rows to pristine null renderConfig/assetUrl.`);
    
    console.log(`[DRY RUN] Run with --confirm to execute.`);
    return;
  }

  // 1. Soft-retire all existing AssetJob rows to DEAD_LETTER (NEVER delete rows)
  const updatedJobs = await prisma.assetJob.updateMany({
    where: {
      stage: { notIn: [JobStage.DEAD_LETTER] },
    },
    data: {
      stage: JobStage.DEAD_LETTER,
      errorMessage: 'superseded by phase-2.5 reset',
    },
  });
  console.log(`[DB] Marked ${updatedJobs.count} AssetJob rows as DEAD_LETTER.`);

  // 2. Clear out any published cosmetics that were generated by the swarm
  // (We identify them because the seed creates them with NO renderConfig)
  const resetCosmetics = await prisma.cosmetic.updateMany({
    where: {
      renderConfig: { not: null as any },
    },
    data: {
      assetUrl: null as any,
      renderConfig: null as any,
    },
  });
  console.log(`[DB] Reset ${resetCosmetics.count} published Cosmetic rows to pristine null renderConfig/assetUrl.`);

  // 3. Delete any generated PNGs from disk EXCEPT the starter ones
  const safeToKeep = ['neon-katana.png', 'nova-crown.png', 'plasma-aura.png', 'void-trail.png'];
  const cosmeticsDir = path.join(process.cwd(), 'public', 'cosmetics');
  
  if (fs.existsSync(cosmeticsDir)) {
    const files = fs.readdirSync(cosmeticsDir);
    for (const f of files) {
      if (f.endsWith('.png') || f.endsWith('.glb')) {
        if (safeToKeep.includes(f)) {
          console.log(`[DISK] Preserving starter asset: ${f}`);
        } else {
          const fp = path.join(cosmeticsDir, f);
          const stat = fs.statSync(fp);
          fs.unlinkSync(fp);
          console.log(`[DISK] Removed synthetic placeholder ${f.endsWith('.png') ? 'PNG' : 'GLB'}: ${f} (${stat.size} bytes)`);
        }
      }
    }
  }

  // 4. Invalidate cache
  invalidateServerCatalogCache();
  console.log('[CACHE] Invalidated in-process server catalog cache.');
  
  console.log('=== FORGE SWARM RESET COMPLETE ===');
}

resetSwarmJobs()
  .catch((e) => {
    console.error('Reset script failed:', e);
    process.exit(1);
  })
  .finally(() => {
    prisma.$disconnect();
  });
