#!/usr/bin/env node
/**
 * trendly-mcp.js — Trendly Model Context Protocol (MCP) Server
 *
 * Exposes Trendly's core runtime functions (workers, Jev gates, approvals,
 * decision logs, calibration snapshots, ledger entries, and workflows)
 * to any MCP-compliant client and local harnesses over stdio JSON-RPC 2.0.
 */
'use strict';

const http = require('node:http');
const https = require('node:https');
const crypto = require('node:crypto');

const TRENDFORGE_API_URL = (process.env.TRENDFORGE_API_URL || 'http://localhost:3000').replace(/\/$/, '');
const BRIDGE_SECRET = process.env.TRENDFORGE_BRIDGE_SECRET || process.env.STARNET_BRIDGE_SECRET || '';
const MCP_PROTOCOL_VERSION = '2025-06-18';
const SERVER_INFO = {
  name: 'trendly-visual-agent-os',
  version: '1.0.0',
};

const TOOLS = [
  {
    name: 'get_worker_status',
    description: 'Fetch real-time health, latency, uptime, and circuit-breaker status for all 5 Trendly production swarm workers (reddit_scraper, prediction_arbitrage, openclaw_deployer, ai_video_maker, micro_saas_builder).',
    inputSchema: {
      type: 'object',
      properties: {
        workerId: {
          type: 'string',
          enum: ['reddit_scraper', 'prediction_arbitrage', 'openclaw_deployer', 'ai_video_maker', 'micro_saas_builder'],
          description: 'Optional filter for a specific worker bay.',
        },
      },
    },
  },
  {
    name: 'list_pending_approvals',
    description: 'List pending human-in-the-loop approvals queued by the Jev decision gate layer awaiting manual review.',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', description: 'Max number of approvals to retrieve (default 20).' },
      },
    },
  },
  {
    name: 'get_decision_log',
    description: 'Query Trendly DecisionLog entries generated by the 7 Jev decision gates (trade_execution, lead_qualification, approval, completion, ledger_verification, tool_routing, model_routing).',
    inputSchema: {
      type: 'object',
      properties: {
        gateType: {
          type: 'string',
          enum: ['trade_execution', 'lead_qualification', 'approval', 'completion', 'ledger_verification', 'tool_routing', 'model_routing'],
          description: 'Filter by specific gate.',
        },
        limit: { type: 'number', description: 'Number of rows to return (default 20).' },
        since: { type: 'string', description: 'ISO date string to filter decisions from.' },
      },
    },
  },
  {
    name: 'execute_worker_task',
    description: 'Dispatch an autonomous task to one of Trendly\'s 5 production swarm workers with specific parameters.',
    inputSchema: {
      type: 'object',
      required: ['agentType'],
      properties: {
        agentType: {
          type: 'string',
          enum: ['reddit_scraper', 'prediction_arbitrage', 'openclaw_deployer', 'ai_video_maker', 'micro_saas_builder'],
          description: 'The target swarm worker bay.',
        },
        parameters: {
          type: 'object',
          description: 'Key-value input parameters for the agent.',
        },
      },
    },
  },
  {
    name: 'approve_task',
    description: 'Approve a pending human-in-the-loop gate approval, allowing the worker to resume execution.',
    inputSchema: {
      type: 'object',
      required: ['approvalId'],
      properties: {
        approvalId: { type: 'string', description: 'ID of the pending approval record.' },
      },
    },
  },
  {
    name: 'reject_task',
    description: 'Reject a pending human-in-the-loop gate approval with a specific reason.',
    inputSchema: {
      type: 'object',
      required: ['approvalId'],
      properties: {
        approvalId: { type: 'string', description: 'ID of the pending approval record.' },
        reason: { type: 'string', description: 'Rejection explanation.' },
      },
    },
  },
  {
    name: 'get_calibration_snapshot',
    description: 'Fetch calibration accuracy metrics per gate and confidence bucket from the CalibrationSnapshot database table.',
    inputSchema: {
      type: 'object',
      properties: {
        gate: { type: 'string', description: 'Gate type to filter snapshots.' },
        days: { type: 'number', description: 'Historical lookup window in days (default 7).' },
      },
    },
  },
  {
    name: 'get_ledger_entries',
    description: 'Retrieve append-only financial ledger entries (LedgerEntry writes) verifying all transactions and agent balances.',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', description: 'Max number of ledger rows (default 50).' },
        since: { type: 'string', description: 'ISO timestamp filter.' },
      },
    },
  },
  {
    name: 'get_workflow_pipelines',
    description: 'List configured multi-worker pipelines connecting worker bays in Trendly.',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'save_workflow_pipeline',
    description: 'Save or create a new multi-worker pipeline (AgentWorkflow) defining authorized data handoffs between bays.',
    inputSchema: {
      type: 'object',
      required: ['name', 'steps'],
      properties: {
        name: { type: 'string', description: 'Pipeline name.' },
        steps: {
          type: 'array',
          description: 'Array of pipeline steps { agentType, parameters } in execution order.',
          items: {
            type: 'object',
            properties: {
              agentType: { type: 'string' },
              parameters: { type: 'object' },
            },
          },
        },
      },
    },
  },
];

// Helper to make signed requests to Trendly backend
async function fetchTrendly(path, options = {}) {
  const url = `${TRENDFORGE_API_URL}${path}`;
  const method = options.method || 'GET';
  const body = options.body ? JSON.stringify(options.body) : null;
  const headers = {
    'Accept': 'application/json',
    ...(options.headers || {}),
  };

  if (body) {
    headers['Content-Type'] = 'application/json';
    if (BRIDGE_SECRET) {
      const hmac = crypto.createHmac('sha256', BRIDGE_SECRET).update(body).digest('hex');
      headers['X-Trendforge-Signature'] = `sha256=${hmac}`;
    }
  }

  const parsedUrl = new URL(url);
  const client = parsedUrl.protocol === 'https:' ? https : http;

  return new Promise((resolve, reject) => {
    const req = client.request(
      url,
      {
        method,
        headers,
        timeout: 10000,
      },
      (res) => {
        let raw = '';
        res.on('data', (c) => (raw += c));
        res.on('end', () => {
          try {
            const data = raw ? JSON.parse(raw) : null;
            resolve({ status: res.statusCode, data, raw });
          } catch (_) {
            resolve({ status: res.statusCode, data: null, raw });
          }
        });
      }
    );

    req.on('error', (err) => reject(err));
    req.on('timeout', () => {
      req.destroy();
      reject(new Error(`Timeout connecting to Trendly at ${url}`));
    });

    if (body) req.write(body);
    req.end();
  });
}

// Tool dispatch table
async function executeTool(name, args = {}) {
  switch (name) {
    case 'get_worker_status': {
      const res = await fetchTrendly('/api/status');
      if (res.status >= 200 && res.status < 300 && res.data) {
        let services = res.data.services || [];
        if (args.workerId) {
          services = services.filter((s) => s.id === args.workerId);
        }
        return {
          systemStatus: res.data.systemStatus || 'OPERATIONAL',
          timestamp: res.data.timestamp,
          workers: services,
        };
      }
      return { error: `Failed to fetch status: HTTP ${res.status}`, raw: res.raw };
    }

    case 'list_pending_approvals': {
      const res = await fetchTrendly('/api/approvals/list');
      if (res.status >= 200 && res.status < 300 && res.data) {
        let pending = res.data.pending || [];
        if (args.limit) pending = pending.slice(0, args.limit);
        return {
          count: pending.length,
          pending,
        };
      }
      return { error: `Failed to list approvals: HTTP ${res.status}`, raw: res.raw };
    }

    case 'get_decision_log': {
      const params = new URLSearchParams();
      if (args.gateType) params.set('gate', args.gateType);
      if (args.limit) params.set('limit', String(args.limit));
      if (args.since) params.set('since', args.since);

      const res = await fetchTrendly(`/api/observability/export?${params.toString()}`);
      if (res.status >= 200 && res.status < 300 && res.data) {
        return res.data;
      }
      return { error: `Failed to fetch decisions: HTTP ${res.status}`, raw: res.raw };
    }

    case 'execute_worker_task': {
      const res = await fetchTrendly('/api/trendforge/dispatch', {
        method: 'POST',
        body: {
          agentGoal: `Execute worker directive on bay: ${args.agentType}`,
          tools: [args.agentType],
          ventureId: 'trendly-visual-os',
          parameters: args.parameters || {},
        },
      });
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'approve_task': {
      const res = await fetchTrendly('/api/approvals/approve', {
        method: 'POST',
        body: { approvalId: args.approvalId },
      });
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'reject_task': {
      const res = await fetchTrendly('/api/approvals/reject', {
        method: 'POST',
        body: { approvalId: args.approvalId, reason: args.reason },
      });
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'get_calibration_snapshot': {
      const params = new URLSearchParams();
      if (args.gate) params.set('gate', args.gate);
      if (args.days) params.set('days', String(args.days));

      const res = await fetchTrendly(`/api/observability/calibration?${params.toString()}`);
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'get_ledger_entries': {
      const params = new URLSearchParams();
      if (args.since) params.set('since', args.since);
      const res = await fetchTrendly(`/api/trendforge/ledger?${params.toString()}`);
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'get_workflow_pipelines': {
      const res = await fetchTrendly('/api/workflows');
      return res.data || { status: res.status, raw: res.raw };
    }

    case 'save_workflow_pipeline': {
      const res = await fetchTrendly('/api/workflows', {
        method: 'POST',
        body: {
          name: args.name,
          steps: args.steps,
        },
      });
      return res.data || { status: res.status, raw: res.raw };
    }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

// JSON-RPC 2.0 Handler
async function handleRpc(request) {
  const { id, method, params } = request;

  if (method === 'initialize') {
    return {
      jsonrpc: '2.0',
      id,
      result: {
        protocolVersion: MCP_PROTOCOL_VERSION,
        capabilities: {
          tools: { listChanged: false },
        },
        serverInfo: SERVER_INFO,
      },
    };
  }

  if (method === 'notifications/initialized') {
    return null; // Notifications have no response
  }

  if (method === 'tools/list') {
    return {
      jsonrpc: '2.0',
      id,
      result: {
        tools: TOOLS,
      },
    };
  }

  if (method === 'tools/call') {
    const { name, arguments: toolArgs } = params || {};
    try {
      const result = await executeTool(name, toolArgs || {});
      return {
        jsonrpc: '2.0',
        id,
        result: {
          content: [
            {
              type: 'text',
              text: JSON.stringify(result, null, 2),
            },
          ],
        },
      };
    } catch (err) {
      return {
        jsonrpc: '2.0',
        id,
        result: {
          isError: true,
          content: [
            {
              type: 'text',
              text: `Error executing ${name}: ${err.message}`,
            },
          ],
        },
      };
    }
  }

  if (method === 'ping') {
    return { jsonrpc: '2.0', id, result: {} };
  }

  return {
    jsonrpc: '2.0',
    id,
    error: {
      code: -32601,
      message: `Method not found: ${method}`,
    },
  };
}

// Stdio Reader
function startStdioServer() {
  let buffer = '';

  process.stdin.setEncoding('utf8');
  process.stdin.on('data', async (chunk) => {
    buffer += chunk;
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop(); // Keep incomplete line

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        const req = JSON.parse(trimmed);
        const res = await handleRpc(req);
        if (res) {
          process.stdout.write(JSON.stringify(res) + '\n');
        }
      } catch (err) {
        process.stderr.write(`[trendly-mcp] Parse error: ${err.message}\n`);
      }
    }
  });

  process.stderr.write(`[trendly-mcp] Server initialized on stdio. Target: ${TRENDFORGE_API_URL}\n`);
}

module.exports = {
  TOOLS,
  executeTool,
  handleRpc,
  startStdioServer,
};

if (require.main === module) {
  startStdioServer();
}
