export const COSMETIC_TIERS = {
  COMMON: { price: 0.99, label: 'Common', color: 'text-gray-300 border-gray-500/30 bg-gray-500/10' },
  RARE: { price: 4.99, label: 'Rare', color: 'text-[#00F0FF] border-[#00F0FF]/30 bg-[#00F0FF]/10' },
  EPIC: { price: 9.99, label: 'Epic', color: 'text-purple-400 border-purple-500/30 bg-purple-500/10' },
  LEGENDARY: { price: 19.99, label: 'Legendary', color: 'text-[#FFD700] border-[#FFD700]/30 bg-[#FFD700]/10' },
  MYTHIC: { price: 0.0, label: 'Mythic (Ultra-Rare)', color: 'text-[#FF007A] border-[#FF007A]/30 bg-[#FF007A]/10' },
};

export type CombatSlot = 'HEAD' | 'EYEWEAR' | 'BODY' | 'AURA' | 'TRAIL' | 'FINISHER';

export interface StatModifiers {
  pwr?: number; // Power: Execution Yield & Raw Damage
  spd?: number; // Speed: Arbitrage Latency & Turn Order
  def?: number; // Defense: Darwinian Survival Resilience
  syn?: number; // Synergy: Neural Intelligence & Combo Multiplier
}

export type CosmeticRenderConfig =
  | { kind: 'layered2d' }
  | {
      kind: 'model3d';
      glbUrl: string;
      scale?: number;
      position?: [number, number, number];
      rotation?: [number, number, number];
      emissive?: { color: string; intensity: number };
    };

export interface CatalogItem {
  id: string;
  name: string;
  category: 'SKIN' | 'HEADWEAR' | 'EYEWEAR' | 'WINGS' | 'AURA' | 'ANIMATION'; // backward compatible
  slot: CombatSlot;
  rarity: 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'MYTHIC';
  price: number;
  image: string;
  animated?: string;
  artPending?: boolean;
  previewUrl?: string; // backward compatible alias
  desc: string;
  unlockMethod: string;
  statModifiers: StatModifiers;
  render?: CosmeticRenderConfig;
}

export function resolveRenderKind(item?: CatalogItem | null): 'layered2d' | 'model3d' {
  if (!item || !item.render) return 'layered2d';
  return item.render.kind;
}

export const COSMETICS_CATALOG: CatalogItem[] = [
  // 1. BODY / SKINS (10 items) -> Grants +PWR, +DEF
  {
    id: 'skin_neon_cyber',
    name: 'Neon Cyberpunk Operative',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/skin_neon_cyber.png',
    artPending: true,
    desc: 'Sleek dark suit with glowing electric cyan circuit filaments.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 6, spd: 4 },
  },
  {
    id: 'skin_quantum_void',
    name: 'Quantum Void Android',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/skin_quantum_void.png',
    artPending: true,
    desc: 'Chameleon alloy chassis with pulsing reactor core.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 8, syn: 5 },
  },
  {
    id: 'skin_wallstreet_titan',
    name: 'Wall Street Sovereign Titan',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/skin_wallstreet_titan.png',
    artPending: true,
    desc: '24K gold-plated executive armor with silk tie.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 12, def: 8 },
  },
  {
    id: 'skin_cosmic_nebula',
    name: 'Cosmic Nebula Entity',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'MYTHIC',
    price: 0.0,
    image: '/cosmetics/skin_cosmic_nebula.png',
    artPending: true,
    desc: 'Translucent dimensional form drifting with star clusters.',
    unlockMethod: 'LEADERBOARD_REWARD',
    statModifiers: { pwr: 15, syn: 10, def: 5 },
  },
  {
    id: 'skin_matte_hacker',
    name: 'Matte Stealth Hacker',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/skin_matte_hacker.png',
    artPending: true,
    desc: 'Non-reflective carbon fiber tactical hoodie.',
    unlockMethod: 'QUEST',
    statModifiers: { spd: 3, def: 2 },
  },
  {
    id: 'skin_solana_solider',
    name: 'Solana Speed Soldier',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/skin_solana_solider.png',
    artPending: true,
    desc: 'High-frequency gradient battle armor.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 7, pwr: 3 },
  },
  {
    id: 'skin_crypto_samurai',
    name: 'DeFi Ronin Samurai',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/neon-katana.png', // Reference starter asset mapped
    artPending: false,
    desc: 'Traditional cyber-infused samurai plate with glowing alloy weave.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 9, spd: 5 },
  },
  {
    id: 'skin_mev_phantom',
    name: 'MEV Phantom Arbitrageur',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/skin_mev_phantom.png',
    artPending: true,
    desc: 'Glitched spectral body that phases through mempools.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 12, syn: 6 },
  },
  {
    id: 'skin_pixel_trader',
    name: '8-Bit Retro Tycoon',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/skin_pixel_trader.png',
    artPending: true,
    desc: 'Chunky arcade aesthetic from the genesis era.',
    unlockMethod: 'QUEST',
    statModifiers: { def: 3, syn: 2 },
  },
  {
    id: 'skin_bio_synth',
    name: 'Bio-Synthetic Pioneer',
    category: 'SKIN',
    slot: 'BODY',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/skin_bio_synth.png',
    artPending: true,
    desc: 'Organic emerald green neural matrix suit.',
    unlockMethod: 'STORE',
    statModifiers: { def: 6, syn: 4 },
  },

  // 2. HEAD / HEADWEAR (10 items) -> Grants +SPD, +SYN
  {
    id: 'head_tactical_visor',
    name: 'Holographic Tactical Visor',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/head_tactical_visor.png',
    artPending: true,
    desc: 'Heads-up display highlighting real-time market spreads.',
    unlockMethod: 'QUEST',
    statModifiers: { spd: 3, syn: 2 },
  },
  {
    id: 'head_diamond_crown',
    name: 'Solana Diamond Crown',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/nova-crown.png', // Reference starter asset mapped
    artPending: false,
    desc: 'Flawless gem-encrusted crown radiating prestige and focus.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 10, pwr: 8 },
  },
  {
    id: 'head_cyber_helmet',
    name: 'Overclocked Cyber Helmet',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/head_cyber_helmet.png',
    artPending: true,
    desc: 'Reinforced ballistic helmet with neural antenna.',
    unlockMethod: 'STORE',
    statModifiers: { def: 7, syn: 5 },
  },
  {
    id: 'head_gold_shades',
    name: 'Golden Aviator Shades',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/head_gold_shades.png',
    artPending: true,
    desc: 'Mirrored polarized lenses reflecting stock charts.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 5, pwr: 3 },
  },
  {
    id: 'head_oni_mask',
    name: 'Cyber Oni Demon Mask',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/head_oni_mask.png',
    artPending: true,
    desc: 'Neon horn mask intimidating rival trading bots.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 8, def: 4 },
  },
  {
    id: 'head_matrix_bandana',
    name: 'Matrix Binary Bandana',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/head_matrix_bandana.png',
    artPending: true,
    desc: 'Green ASCII text streaming across headband.',
    unlockMethod: 'QUEST',
    statModifiers: { syn: 4, spd: 1 },
  },
  {
    id: 'head_halo_light',
    name: 'Angel of Yield Halo',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/head_halo_light.png',
    artPending: true,
    desc: 'Floating golden ring humming with high APR.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 12, def: 5 },
  },
  {
    id: 'head_beret_exec',
    name: 'Venture Capital Beret',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/head_beret_exec.png',
    artPending: true,
    desc: 'Sophisticated bespoke wool headwear.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 4, syn: 5 },
  },
  {
    id: 'head_vr_goggles',
    name: 'Spatial Web4 Goggles',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/head_vr_goggles.png',
    artPending: true,
    desc: 'Dual OLED lens set for immersive metaverse data.',
    unlockMethod: 'QUEST',
    statModifiers: { syn: 3, spd: 2 },
  },
  {
    id: 'head_crown_spikes',
    name: 'Anarchist Spike Tiara',
    category: 'HEADWEAR',
    slot: 'HEAD',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/head_crown_spikes.png',
    artPending: true,
    desc: 'Punk chrome spikes radiating defiance.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 5, spd: 3 },
  },

  // 3. TRAIL / WINGS (10 items) -> Grants +SPD, +DEF
  {
    id: 'wings_overclock',
    name: 'Quantum Overclock Wings',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/void-trail.png', // Reference starter asset mapped
    artPending: false,
    desc: 'Photon thrusters boosting execution latency.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 9, pwr: 4 },
  },
  {
    id: 'wings_angelic',
    name: 'Archangel Plasma Wings',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/wings_angelic.png',
    artPending: true,
    desc: 'Feathered energy wings with pure white light.',
    unlockMethod: 'STORE',
    statModifiers: { def: 10, syn: 7 },
  },
  {
    id: 'wings_cyber_dragon',
    name: 'Cybernetic Dragon Wings',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/wings_cyber_dragon.png',
    artPending: true,
    desc: 'Titanium wings with fiery exhaust vents.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 10, spd: 7 },
  },
  {
    id: 'wings_glider_pack',
    name: 'Solar Glider Jetpack',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/wings_glider_pack.png',
    artPending: true,
    desc: 'Compact micro-turbine propulsion unit.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 6, def: 3 },
  },
  {
    id: 'wings_fairy_sparkle',
    name: 'DeFi Pixie Wings',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/wings_fairy_sparkle.png',
    artPending: true,
    desc: 'Iridescent wings scattering profit pollen.',
    unlockMethod: 'QUEST',
    statModifiers: { spd: 3, syn: 2 },
  },
  {
    id: 'wings_stealth_cape',
    name: 'Shadow Invisibility Cloak',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/wings_stealth_cape.png',
    artPending: true,
    desc: 'Tattered dark cape trailing smoke.',
    unlockMethod: 'STORE',
    statModifiers: { def: 6, spd: 3 },
  },
  {
    id: 'wings_holo_fins',
    name: 'Holographic Aero Fins',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/wings_holo_fins.png',
    artPending: true,
    desc: 'Lightweight stabilization fins for high-speed scraping.',
    unlockMethod: 'QUEST',
    statModifiers: { spd: 4, syn: 1 },
  },
  {
    id: 'wings_void_tentacles',
    name: 'Eldritch Void Spikes',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/wings_void_tentacles.png',
    artPending: true,
    desc: 'Tendrils of pure gravity weaving behind your agent.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 7, syn: 7 },
  },
  {
    id: 'wings_gold_phoenix',
    name: 'Golden Phoenix Crest',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'MYTHIC',
    price: 0.0,
    image: '/cosmetics/wings_gold_phoenix.png',
    artPending: true,
    desc: 'Blazing legendary wings representing market rebirth.',
    unlockMethod: 'TOURNAMENT_CHAMPION',
    statModifiers: { pwr: 12, spd: 10, def: 8 },
  },
  {
    id: 'wings_mech_blade',
    name: 'Gundam Blade Wings',
    category: 'WINGS',
    slot: 'TRAIL',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/wings_mech_blade.png',
    artPending: true,
    desc: 'Articulated wing blades capable of slicing spreads.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 8, spd: 5 },
  },

  // 4. AURA (10 items) -> Grants +PWR, +SPD
  {
    id: 'aura_plasma_fire',
    name: 'Plasma Fire Aura',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/plasma-aura.png', // Reference starter asset mapped
    artPending: false,
    desc: 'Intense magenta-violet flame enveloping the agent.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 8, spd: 5 },
  },
  {
    id: 'aura_matrix_glitch',
    name: 'Matrix Digital Rain Glitch',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/aura_matrix_glitch.png',
    artPending: true,
    desc: 'Cascading lime-green binary data and spatial glitches.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 12, spd: 6 },
  },
  {
    id: 'aura_gold_sparkles',
    name: 'Golden Wealth Sparkles',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/aura_gold_sparkles.png',
    artPending: true,
    desc: 'Floating gold coin dust and dollar glyphs.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 6, syn: 3 },
  },
  {
    id: 'aura_electric_storm',
    name: 'Tesla Lightning Orbit',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/aura_electric_storm.png',
    artPending: true,
    desc: 'High-voltage electric arcs crackling around chassis.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 8, pwr: 6 },
  },
  {
    id: 'aura_scan_beam',
    name: 'Holographic Scan Beam',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/aura_scan_beam.png',
    artPending: true,
    desc: 'Periodic cyan radar sweep scanning surroundings.',
    unlockMethod: 'QUEST',
    statModifiers: { syn: 3, def: 2 },
  },
  {
    id: 'aura_cosmic_dust',
    name: 'Interstellar Nebula Fog',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/aura_cosmic_dust.png',
    artPending: true,
    desc: 'Swirling purple cosmic gas with micro-stars.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 6, def: 3 },
  },
  {
    id: 'aura_blood_rage',
    name: 'Berserker Crimson Pulse',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/aura_blood_rage.png',
    artPending: true,
    desc: 'Aggressive red heartbeat wave for volatile trades.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 7, spd: 4 },
  },
  {
    id: 'aura_frost_zero',
    name: 'Absolute Zero Frost',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/aura_frost_zero.png',
    artPending: true,
    desc: 'Freezing vapor and crystalline snowflake trails.',
    unlockMethod: 'QUEST',
    statModifiers: { def: 4, syn: 2 },
  },
  {
    id: 'aura_void_blackhole',
    name: 'Singularity Micro-Blackhole',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'MYTHIC',
    price: 0.0,
    image: '/cosmetics/aura_void_blackhole.png',
    artPending: true,
    desc: 'Warps light and space around the agent.',
    unlockMethod: 'SURVIVAL_MASTER',
    statModifiers: { pwr: 14, syn: 10, def: 8 },
  },
  {
    id: 'aura_synthwave_sun',
    name: '80s Synthwave Grid Glow',
    category: 'AURA',
    slot: 'AURA',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/aura_synthwave_sun.png',
    artPending: true,
    desc: 'Retro sunset neon glow radiating outward.',
    unlockMethod: 'QUEST',
    statModifiers: { spd: 3, pwr: 2 },
  },

  // 5. FINISHER / ANIMATION (10 items) -> Grants +SYN, +PWR
  {
    id: 'anim_hover_idle',
    name: 'Hover Levitation Idle',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/anim_hover_idle.png',
    artPending: true,
    desc: 'Agent effortlessly levitates in meditative focus.',
    unlockMethod: 'QUEST',
    statModifiers: { syn: 3, def: 2 },
  },
  {
    id: 'anim_profit_rain',
    name: 'Profit Rain Celebration',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/anim_profit_rain.png',
    artPending: true,
    desc: 'Agent showers stacks of USDC upon winning trades.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 8, syn: 6 },
  },
  {
    id: 'anim_combat_stance',
    name: 'Cyber Combat Stance',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/anim_combat_stance.png',
    artPending: true,
    desc: 'Dynamic battle-ready posture for arena duels.',
    unlockMethod: 'QUEST',
    statModifiers: { def: 4, spd: 2 },
  },
  {
    id: 'anim_hacker_typing',
    name: 'Hacker Terminal Blitz',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/anim_hacker_typing.png',
    artPending: true,
    desc: 'Furious typing on floating holographic keyboards.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 6, syn: 5 },
  },
  {
    id: 'anim_breakdance',
    name: 'Cyberspace Breakdance',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/anim_breakdance.png',
    artPending: true,
    desc: 'Windmills and headspins in zero-gravity.',
    unlockMethod: 'STORE',
    statModifiers: { spd: 9, syn: 8 },
  },
  {
    id: 'anim_meditation',
    name: 'Zen Node Harmony',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'RARE',
    price: 4.99,
    image: '/cosmetics/anim_meditation.png',
    artPending: true,
    desc: 'Cross-legged levitation with orbiting data rings.',
    unlockMethod: 'STORE',
    statModifiers: { def: 7, syn: 6 },
  },
  {
    id: 'anim_salute',
    name: 'Military Commander Salute',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'COMMON',
    price: 0.99,
    image: '/cosmetics/anim_salute.png',
    artPending: true,
    desc: 'Crisp tactical salute when completing tasks.',
    unlockMethod: 'QUEST',
    statModifiers: { def: 3, pwr: 2 },
  },
  {
    id: 'anim_guitar_solo',
    name: 'Neon Guitar Shred',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'EPIC',
    price: 9.99,
    image: '/cosmetics/anim_guitar_solo.png',
    artPending: true,
    desc: 'Solo riffs on a glowing laser bass.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 7, spd: 6 },
  },
  {
    id: 'anim_superhero_landing',
    name: 'Titan Superhero Landing',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'LEGENDARY',
    price: 19.99,
    image: '/cosmetics/anim_superhero_landing.png',
    artPending: true,
    desc: 'Cratering ground entrance with dust shockwave.',
    unlockMethod: 'STORE',
    statModifiers: { pwr: 11, def: 8 },
  },
  {
    id: 'anim_matrix_dodge',
    name: 'Bullet-Time Matrix Dodge',
    category: 'ANIMATION',
    slot: 'FINISHER',
    rarity: 'MYTHIC',
    price: 0.0,
    image: '/cosmetics/anim_matrix_dodge.png',
    artPending: true,
    desc: 'Slow-motion backbend dodging market volatility.',
    unlockMethod: 'EASTER_EGG',
    statModifiers: { spd: 14, syn: 10, def: 6 },
  },

  // EYEWEAR (6 items) -> Grants +SYN, +SPD
  {
    id: 'eyes_holo_monocle',
    name: 'Holographic Monocle of Markets',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'RARE',
    price: 6.99,
    image: '/cosmetics/eyes_holo_monocle.png',
    artPending: true,
    desc: 'A rotating HUD monocle streaming live ticker data across one eye.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 7, spd: 2 },
  },
  {
    id: 'eyes_cyber_visors',
    name: 'Slate Cyber Visor',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'COMMON',
    price: 2.99,
    image: '/cosmetics/eyes_cyber_visors.png',
    artPending: true,
    desc: 'Matte wrap-around visor with a single cyan scanline.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 3, spd: 3 },
  },
  {
    id: 'eyes_quantum_goggles',
    name: 'Quantum Recon Goggles',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'EPIC',
    price: 12.99,
    image: '/cosmetics/eyes_quantum_goggles.png',
    artPending: true,
    desc: 'Dual-lens goggles parsing arbitrage windows before they exist.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 9, spd: 5 },
  },
  {
    id: 'eyes_gold_seer',
    name: 'Golden Seer Lenses',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'LEGENDARY',
    price: 24.99,
    image: '/cosmetics/eyes_gold_seer.png',
    artPending: true,
    desc: 'Forged for those who saw the trend before it trended.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 12, pwr: 4 },
  },
  {
    id: 'eyes_void_shades',
    name: 'Void Stepper Shades',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'RARE',
    price: 5.99,
    image: '/cosmetics/eyes_void_shades.png',
    artPending: true,
    desc: 'Pitch-black shades. Nobody knows what you are looking at. That is the point.',
    unlockMethod: 'STORE',
    statModifiers: { def: 4, syn: 4 },
  },
  {
    id: 'eyes_plasma_spectacles',
    name: 'Plasma Spectacles',
    category: 'EYEWEAR',
    slot: 'EYEWEAR',
    rarity: 'MYTHIC',
    price: 39.99,
    image: '/cosmetics/eyes_plasma_spectacles.png',
    artPending: true,
    desc: 'Contained plasma arcs dance between the lenses as you think.',
    unlockMethod: 'STORE',
    statModifiers: { syn: 14, spd: 6, pwr: 3 },
  },
];
