'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const wm = require(path.join(root, 'frontend/app/worldmodel.js'));
const props = require(path.join(root, 'frontend/app/propsprites.js'));
wm.setPropRules(props.spec);
const target = path.join(root, 'dev/.scratch-workspace/agent.save.json');
const original = fs.readFileSync(target, 'utf8'), save = JSON.parse(original);
const station = save.doc.station;
assert.equal(station.rooms.r1.name, 'COMMAND DECK', 'only the art preview may be expanded');
assert.equal(station.props.find(p => p.id === 'p1').agentId, 'agent');
assert.ok(station.props.every(p => ['desk','desk2','chair','bridge_consolebank','bridge_tacticaltable','bridge_equipmentbay','bridge_deckperimeter'].includes(p.t)), 'keep unexpected user additions');
station.props = require('./command-deck.cjs')();
station._nid = Math.max(station._nid || 0, 40);
const model = wm.deserialize(station);
for (const p of station.props) assert.equal(model.canPlaceProp(p.t,p.x,p.y,p.w,p.h,p.id).ok,true,'placement '+p.id);
const backup = path.join(__dirname, 'preview-before-bridge-' + Date.now() + '.json');
fs.writeFileSync(backup, original);
save.updatedAt = save.savedAt = save.doc.updatedAt = Date.now();
fs.writeFileSync(target, JSON.stringify(save, null, 2));
console.log(JSON.stringify({ props:station.props.length, backup }));
