import assert from 'node:assert/strict';
import { replayTurn, startReplayProvider, validateResume, SAMPLE, DRAFT, MODEL } from '../dev/value-loop-replay.mjs';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const resumeRoot = mkdtempSync(join(tmpdir(), 'starnet-resume-validation-'));
mkdirSync(join(resumeRoot, 'workspace')); mkdirSync(join(resumeRoot, 'client-notes'));
const savedPath = join(resumeRoot, 'workspace', 'agent.save.json'), rosterPath = join(resumeRoot, 'workspace', 'agent.roster.json'), notesPath = join(resumeRoot, 'client-notes', 'weekly-notes.md');
writeFileSync(savedPath, JSON.stringify({ doc: { retained: 'exact prior state' } }));
writeFileSync(rosterPath, JSON.stringify({ agents: [{ model: MODEL }] }));
writeFileSync(notesPath, SAMPLE);
const beforeResume = [savedPath, rosterPath, notesPath].map(p => ({ bytes: readFileSync(p, 'utf8'), mtime: statSync(p).mtimeMs }));
assert.equal(validateResume(resumeRoot).workspace, join(resumeRoot, 'workspace'));
assert.deepEqual([savedPath, rosterPath, notesPath].map(p => ({ bytes: readFileSync(p, 'utf8'), mtime: statSync(p).mtimeMs })), beforeResume);
assert.throws(() => validateResume('relative-path'), /absolute/);
assert.throws(() => validateResume(join(resumeRoot, 'missing')));
writeFileSync(rosterPath, JSON.stringify({ agents: [{ model: 'external/model' }] }));
assert.throws(() => validateResume(resumeRoot), /local replay model/);
writeFileSync(rosterPath, JSON.stringify({ agents: [{ model: MODEL }] }));
writeFileSync(notesPath, 'not fixture notes');
assert.throws(() => validateResume(resumeRoot), /not the replay fixture/);
writeFileSync(notesPath, SAMPLE); writeFileSync(savedPath, '{broken');
assert.throws(() => validateResume(resumeRoot));
const tools = ['brief_proceed', 'fs.read', 'fs.write'].map(name => ({ type: 'function', function: { name } }));
const prompt = 'Task: Draft a weekly client update\nPasted source: ' + SAMPLE;
const messages = [{ role: 'user', content: prompt }];
assert.equal(replayTurn({ messages: [{ role: 'user', content: 'background reflection' }], tools }).tool, undefined);
assert.equal(replayTurn({ messages, tools }).tool, 'brief_proceed');
messages.push({ role: 'assistant', tool_calls: [{ id: 'one', function: { name: 'brief_proceed' } }] }, { role: 'tool', tool_call_id: 'one', content: '{"ok":true}' });
assert.equal(replayTurn({ messages, tools }).tool, 'fs.write');
assert.equal(replayTurn({ messages, tools }).args.content, DRAFT);
messages.push({ role: 'assistant', tool_calls: [{ id: 'two', function: { name: 'fs.write' } }] }, { role: 'tool', tool_call_id: 'two', content: '{"ok":true}' });
assert.match(replayTurn({ messages, tools }).text, /Saved deliverable: weekly-client-update.md/);
messages[messages.length - 1].content = '{"ok":false,"error":"denied"}';
assert.match(replayTurn({ messages, tools }).text, /stopped after a tool error/);
assert.doesNotMatch(replayTurn({ messages, tools }).text, /Saved deliverable/);
const folderMessages = [{ role: 'user', content: 'Task: Draft a weekly client update\nSource: the user selected this approved folder: "C:\\\\notes".' }, ...messages.slice(1, 3)];
assert.equal(replayTurn({ messages: folderMessages, tools }).tool, 'fs.read');
assert.ok(replayTurn({ messages: folderMessages, tools }).args.path.endsWith('weekly-notes.md'));
assert.match(replayTurn({ messages: [{ role: 'user', content: prompt }], tools: [] }).text, /file-write tool was unavailable/);
assert.match(replayTurn({ messages: [{ role: 'user', content: 'Task: Draft a weekly client update\nRandom real data' }], tools: [] }).text, /Paste the printed/);
const provider = await startReplayProvider();
try {
  const res = await fetch(provider.base + '/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: MODEL, messages: [{ role: 'user', content: prompt }], tools }) });
  assert.equal(res.status, 200);
  const wire = await res.text();
  assert.match(wire, /brief_proceed/);
  assert.match(wire, /\[DONE\]/);
  assert.equal(provider.requests.length, 1);
} finally { await new Promise(resolve => provider.server.close(resolve)); }
console.log('value-loop-replay: assertions passed');
