'use strict';
const assert = require('node:assert/strict');
const V = require('../frontend/app/workview.js');
const stream = {id:'s',kind:'task',title:'Weekly update',runIds:['r'],lastActiveAt:1};
assert.equal(V.project({streams:[stream]}).needsYou[0].status, 'Run outcome is unconfirmed');
assert.equal(V.project({streams:[{...stream,lastRunOk:true}]}).finished.length,1);
assert.match(V.project({streams:[{...stream,lastRunOk:true}]}).finished[0].status,/review result/);
assert.equal(V.project({streams:[{...stream,lane:'shipped'}],channels:{s:{busy:true,runId:'r'}}}).doing.length,1);
assert.equal(V.project({streams:[stream],channels:{s:{busy:true,runId:null}}}).doing[0].status,'Connecting');
assert.equal(V.project({streams:[stream],channels:{s:{busy:true,pending:{},runId:'r'}}}).needsYou.length,1);
const joined=V.project({streams:[stream],deliverables:[{id:'a',runId:'r',files:[{path:'update.md'}]}]});
assert.equal(joined.items.length,1); assert.equal(joined.items[0].artifacts.length,1);
assert.equal(V.project({streams:[{...stream,archived:true}]}).items.length,0);
assert.equal(V.project({streams:[{id:'empty',kind:'chat',runIds:[]}]}).items.length,0);
assert.equal(V.routineView({enabled:true,nextRunAt:'tomorrow'},false).next,'');
assert.equal(V.routineView({enabled:false,lastRunAt:1,lastStatus:'error'},true).status,'Paused');
assert.equal(V.stationView(null).known,false);
assert.equal(V.stationView({evolution:{name:'DRIFT'},outcomes:[{title:'model says done'}]}).outcomes.length,0);
assert.equal(V.stationView({evolution:{name:'VECTOR'},outcomes:[{sourceId:'q',evidence:'file verified',verifiedBy:'harness-contract',title:'Update delivered',at:1}]}).reason,'Update delivered');
assert.equal(V.project({streams:[{...stream,lastRunOk:true}],deliverables:[{id:'review',runId:'r',status:'pending'}]}).needsYou.length,1);
assert.equal(V.routineView({enabled:true,nextRunAt:'tomorrow'},{enabled:true,halted:true}).status,'Stopped by E-STOP');
assert.equal(V.routineView({enabled:true,nextRunAt:'tomorrow'},{enabled:true,halted:true}).next,'');
assert.equal(V.routineView({enabled:true},{enabled:true,health:{healthy:false}}).status,'Scheduler health unconfirmed');
console.log('workview.test: OK (19 assertions)');
