/* node test/xp-upgrade.test.js — THE UPGRADE GUARD for the leveling lane.

   The question this file exists to answer: when a Commander who has been playing on a SHIPPED build updates,
   does anything they earned move? Levels are monotonic and user-approval-only by law; XP, confidence and the
   operational counters are a record of real work they really did. The lane added meters (S2 RELIABILITY,
   S5 PRACTICE), a briefing credential (S3), five milestones and a boot-time trophy reconcile (S4) — every one
   of which reads the SAME persisted stats object those old saves already contain.

   So the invariant, and it is absolute: **the update may only ADD. Never a lost level, never a moved XP total,
   never a changed confidence, never a decremented counter, never an un-lit badge, and never a fabricated
   number for a meter whose evidence the old save does not contain.**

   The fixtures below are literal v0.7.0-shaped stats — the exact shape frontend/app/xp.js `fresh()` produced at
   tag 87b61564 (no runsOwned/runsWon/runsFaulted/runsNeutral, since those counters did not exist), carrying
   only the nine milestone ids that build knew about. They are hand-written on purpose: a fixture generated by
   the current engine would silently track any future change to the very thing under test. */
'use strict';
const A = require('./_assert.js');
const Xp = require('../frontend/app/xp.js');

// the nine badges the shipped v0.7.0 build knew about — a save can hold no others.
const V070_MILESTONES = ['first_light', 'approved', 'pack_rat', 'archivist', 'workhorse', 'centurion', 'night_shift', 'trusted', 'veteran'];

/* Four real shapes of Commander, in the v0.7.0 save shape. Counters carry only the keys that build wrote:
   runs / tasksDone / toolsOk / memWrites / memReused / delivered / positiveFeedback / negativeFeedback. */
const SAVES = {
  'long-time hero': {
    xp: 412, level: 4, lifetimeXp: 412, confidence: 99.2, samples: 15,
    counters: { runs: 60, tasksDone: 54, toolsOk: 180, memWrites: 8, memReused: 54, positiveFeedback: 15, delivered: 3 },
    milestones: ['first_light', 'approved', 'pack_rat', 'archivist', 'workhorse', 'night_shift', 'trusted'],
    run: { id: null, usedMemory: false }
  },
  'mid-game user': {
    xp: 40, level: 1, lifetimeXp: 40, confidence: 71.9, samples: 2,
    counters: { runs: 9, tasksDone: 8, toolsOk: 30, positiveFeedback: 2 },
    milestones: ['first_light', 'approved'],   // both fired live on the old build, as they would have
    run: { id: null, usedMemory: false }
  },
  'brand new': {
    xp: 0, level: 1, lifetimeXp: 0, confidence: 50, samples: 0,
    counters: { runs: 1, tasksDone: 1 }, milestones: ['first_light'], run: { id: null, usedMemory: false }
  },
  'unlucky (a misconfigured station: every run 404d)': {
    xp: 0, level: 1, lifetimeXp: 0, confidence: 50, samples: 0,
    counters: { runs: 12, tasksDone: 0 }, milestones: [], run: { id: null, usedMemory: false }
  },
  'veteran who is past every old bar': {
    xp: 2400, level: 10, lifetimeXp: 2400, confidence: 96, samples: 40,
    counters: { runs: 130, tasksDone: 120, toolsOk: 900, memWrites: 40, memReused: 100, delivered: 12, positiveFeedback: 40, negativeFeedback: 3 },
    milestones: V070_MILESTONES.slice(),   // every badge that build had, already lit
    run: { id: null, usedMemory: false }
  },
};

const FROZEN = ['xp', 'level', 'lifetimeXp', 'confidence', 'samples'];

for (const [who, before] of Object.entries(SAVES)) {
  const snapshot = JSON.parse(JSON.stringify(before));
  const after = Xp.reconcile(before).stats;

  // 1. NOTHING THE COMMANDER EARNED MOVES.
  for (const k of FROZEN) A.eq(after[k], snapshot[k], who + ': ' + k + ' is untouched by the update');
  for (const k of Object.keys(snapshot.counters)) A.eq(after.counters[k], snapshot.counters[k], who + ': counter ' + k + ' is untouched');
  A.eq(Xp.compute(after).level, Xp.compute(snapshot).level, who + ': the rendered level is identical before and after');
  A.eq(Xp.compute(after).confLabel, Xp.compute(snapshot).confLabel, who + ': the satisfaction readout is identical');

  // 2. NO BADGE IS EVER UN-LIT.
  for (const m of snapshot.milestones) A.ok(after.milestones.indexOf(m) !== -1, who + ': keeps the earned badge ' + m);
  A.eq(after.milestones.length, new Set(after.milestones).size, who + ': the update never duplicates a badge id');

  // 3. ANY NEWLY LIT BADGE IS ONE THE RECORD GENUINELY EARNED — the reconcile cannot invent one.
  const gained = after.milestones.filter(m => snapshot.milestones.indexOf(m) === -1);
  for (const id of gained) {
    const def = Xp.MILESTONES.find(m => m.id === id);
    A.ok(def && def.when(after.counters, after), who + ': newly lit ' + id + ' actually satisfies its own predicate');
  }

  // 4. IDEMPOTENT — every subsequent boot is a no-op, so the trophy case cannot drift or re-announce.
  A.eq(Xp.reconcile(after).earned, [], who + ': a second boot earns nothing more');
  A.eq(JSON.stringify(Xp.reconcile(after).stats), JSON.stringify(after), who + ': a second boot changes nothing at all');

  // 5. THE INPUT SAVE IS NOT MUTATED (the caller decides when state changes, not the engine).
  A.eq(JSON.stringify(before), JSON.stringify(snapshot), who + ': reconcile never mutates the save handed to it');

  // 6. NO METER FABRICATES A NUMBER IT HAS NO EVIDENCE FOR. The S2 counters did not exist in v0.7.0, so
  //    RELIABILITY must read calibrating for EVERY legacy save — including the veteran with 120 shipped
  //    tasks, whose old `runs`/`tasksDone` pair would have rendered a confident, wrong percentage.
  const rel = Xp.reliability(after);
  A.eq(rel.known, false, who + ': RELIABILITY is calibrating on a pre-S2 save, never a number derived from old counters');
  A.eq(rel.label, '—', who + ': …and renders a dash');
  A.eq(rel.pct, null, who + ': …with no percentage at all');
  // …and so the harness-observed badge cannot light off a legacy record either.
  A.eq(after.milestones.indexOf('dependable'), -1, who + ': DEPENDABLE cannot be back-granted — the evidence for it did not exist');
  // PRACTICE likewise says nothing until a skillbase is actually read.
  A.eq(Xp.practice(null).known, false, who + ': PRACTICE reports unknown until the skillbase is read');
}

// The two badges a legacy record CAN honestly back-earn, spelled out on the mid-game fixture.
{
  const g = Xp.reconcile(SAVES['mid-game user']).earned;
  A.eq(g, ['still_here', 'hands_on'], 'the mid-game save back-earns exactly STILL HERE (8 tasks) and HANDS ON (30 tool calls)');
}
// A user already past a NEW bar gets it immediately rather than being asked to re-earn it.
{
  const g = Xp.reconcile(SAVES['veteran who is past every old bar']).earned;
  A.ok(g.indexOf('still_here') !== -1 && g.indexOf('hands_on') !== -1 && g.indexOf('long_memory') !== -1 && g.indexOf('seasoned') !== -1,
    'a Lv10 veteran back-earns every new badge their record already cleared, not one to grind again');
}

/* 7. NO LEGACY SHAPE CRASHES. Saves in the wild are older, hand-edited, half-migrated and occasionally
      corrupt; a growth meter must degrade, never throw, or the dossier takes the whole app down with it. */
const ODD = {
  'stats with no counters at all': { xp: 10, level: 1, lifetimeXp: 10, confidence: 50, samples: 1, milestones: [] },
  'stats with no milestones array': { xp: 10, level: 1, lifetimeXp: 10, confidence: 50, samples: 1, counters: { tasksDone: 9 } },
  'a v0.6-era run buffer': { xp: 0, level: 1, lifetimeXp: 0, confidence: 50, samples: 0, counters: {}, milestones: [], run: { id: null, toolXp: 0 } },
  'an empty object': {},
  'a corrupted save': { xp: Infinity, level: NaN, lifetimeXp: NaN, confidence: Infinity, samples: NaN, counters: { tasksDone: 7 }, milestones: [] },
  'milestone ids this build has never heard of': { xp: 0, level: 1, lifetimeXp: 0, confidence: 50, samples: 0, counters: {}, milestones: ['from_some_other_branch', 'first_light'] },
};
for (const [what, save] of Object.entries(ODD)) {
  let out = null;
  try { out = Xp.reconcile(save); } catch (e) { out = null; }
  A.ok(out && out.stats, 'reconcile survives ' + what);
  A.ok(Number.isFinite(out.stats.level) && Number.isFinite(out.stats.xp) && Number.isFinite(out.stats.confidence), 'reconcile yields finite meters for ' + what);
  for (const fn of ['compute', 'reliability', 'credential', 'milestones']) {
    let ok = true; try { Xp[fn](out.stats); } catch (e) { ok = false; }
    A.ok(ok, Xp[fn] && fn + '() survives ' + what);
  }
}
// an unknown stored id is carried, not crashed on, and simply is not rendered by a build that lacks its badge.
{
  const r = Xp.reconcile(ODD['milestone ids this build has never heard of']).stats;
  A.ok(r.milestones.indexOf('from_some_other_branch') !== -1, 'an unrecognised badge id is preserved, never silently dropped from the save');
  A.eq(Xp.milestones(r).filter(m => m.id === 'from_some_other_branch').length, 0, '…and simply does not render on a build that has no such badge');
}

/* 8. THE ROSTER CREDENTIAL (S3) IS EARNED-ONLY ON LEGACY SAVES TOO — an updating Commander's specialists must
      not suddenly be described to the lead by a rating nobody gave them. */
A.eq(Xp.credential(SAVES['brand new']).text, '', 'a new agent publishes no credential to the dispatch briefing');
A.eq(Xp.credential(SAVES['unlucky (a misconfigured station: every run 404d)']).text, '', 'an agent whose every run failed publishes nothing — never a rank');
A.eq(Xp.credential(SAVES['mid-game user']).text, '5+ tasks shipped', 'a legacy mid-game agent publishes only the tier its record proves — no finish rate it has no counters for');

A.report('xp-upgrade.test');
