import { UnitEconomicsModel } from './types';

export const FULL_FINANCIAL_MODELS: Record<string, UnitEconomicsModel> = {
  'quick-wins-voice': {
    pathway: 'QUICK_WINS',
    playName: 'AI Voice Receptionist for Contractors',
    targetPrice: 750,
    closeRateCold: 0.15,
    leadsNeededPerClose: 20,
    humanTimeMinutes: 45,
    aiProcessingTimeMinutes: 12,
    netProfitPerDeal: 712.5,
    effectiveHourlyRate: 950,
    month1Revenue: 2250,
    month3Revenue: 4500,
    month12Revenue: 9000,
  },
  'quick-wins-gbp': {
    pathway: 'QUICK_WINS',
    playName: 'Google Business Profile AI Pack',
    targetPrice: 497,
    closeRateCold: 0.2,
    leadsNeededPerClose: 20,
    humanTimeMinutes: 30,
    aiProcessingTimeMinutes: 8,
    netProfitPerDeal: 472.15,
    effectiveHourlyRate: 944,
    month1Revenue: 2485,
    month3Revenue: 4970,
    month12Revenue: 9940,
  },
  'video-local-business': {
    pathway: 'VIDEO_EMPIRE',
    playName: 'Play 1: Local Business Video Packages',
    targetPrice: 397,
    closeRateCold: 0.15,
    leadsNeededPerClose: 25,
    humanTimeMinutes: 5,
    aiProcessingTimeMinutes: 10,
    netProfitPerDeal: 397,
    effectiveHourlyRate: 4705,
    month1Revenue: 1191,
    month3Revenue: 3970,
    month12Revenue: 12704,
  },
  'video-creator-clipping': {
    pathway: 'VIDEO_EMPIRE',
    playName: 'Play 2: Creator Clipping Service',
    targetPrice: 797,
    closeRateCold: 0.2,
    leadsNeededPerClose: 15,
    humanTimeMinutes: 30,
    aiProcessingTimeMinutes: 30,
    netProfitPerDeal: 797,
    effectiveHourlyRate: 1594,
    month1Revenue: 1594,
    month3Revenue: 6376,
    month12Revenue: 23910,
  },
  'video-ecommerce-ugc': {
    pathway: 'VIDEO_EMPIRE',
    playName: 'Play 3: E-Commerce UGC Ads',
    targetPrice: 997,
    closeRateCold: 0.18,
    leadsNeededPerClose: 20,
    humanTimeMinutes: 40,
    aiProcessingTimeMinutes: 20,
    netProfitPerDeal: 997,
    effectiveHourlyRate: 1495,
    month1Revenue: 1994,
    month3Revenue: 4985,
    month12Revenue: 24925,
  },
  'video-coach-multiplication': {
    pathway: 'VIDEO_EMPIRE',
    playName: 'Play 4: Coach Content Multiplication',
    targetPrice: 1497,
    closeRateCold: 0.15,
    leadsNeededPerClose: 20,
    humanTimeMinutes: 45,
    aiProcessingTimeMinutes: 30,
    netProfitPerDeal: 1497,
    effectiveHourlyRate: 1996,
    month1Revenue: 1497,
    month3Revenue: 5988,
    month12Revenue: 22455,
  },
  'automated-assets-suite': {
    pathway: 'AUTOMATED_ASSETS',
    playName: 'Marketplace, Referrals & Micro-SaaS',
    targetPrice: 79,
    closeRateCold: 0.05,
    leadsNeededPerClose: 0,
    humanTimeMinutes: 60,
    aiProcessingTimeMinutes: 180,
    netProfitPerDeal: 63.2,
    effectiveHourlyRate: 850,
    month1Revenue: 392,
    month3Revenue: 3181,
    month12Revenue: 11500,
  },
};

export function getWeeklyIntelligenceReport() {
  return {
    weekRange: 'Aug 25 - Sep 01',
    totalPipelineRevenue: 2340,
    breakdown: [
      { pathway: 'Quick Wins', amount: 750, deal: '1 HVAC Voice Receptionist Closed' },
      { pathway: 'Video Empire', amount: 1194, deal: '3 Local Business Retainers Active' },
      { pathway: 'Automated Assets', amount: 396, deal: 'Marketplace Royalties + Referrals' },
    ],
    topOutreachFramework: 'Framework 1 (Free Sample Pitch) — 23% response rate',
    keyRecommendation:
      'Double down on Emergency HVAC and Dental niches. 3 new high-intent prospects were indexed this morning. Syndicate your winning HVAC setup guide to Whop for $69 passive listings.',
  };
}