import { PlatformScoutMatrix } from './types';

export function getPlatformArbitrageMatrix(): PlatformScoutMatrix[] {
  return [
    {
      platform: 'Whop',
      category: 'DIGITAL_PRODUCT',
      payoutPercentage: 95,
      payoutSpeed: 'Instant to 3 business days',
      audienceSize: '500,000+ active digital buyers',
      easeOfListing: 9,
      competitionLevel: 5,
      trendingDirection: 'UP',
      recommendationScore: 94,
      monthlyPotential: '$1,500 – $7,500/mo',
      recommendedPricing: '$49.00 – $99.00/license',
    },
    {
      platform: 'Gumroad',
      category: 'DIGITAL_PRODUCT',
      payoutPercentage: 90,
      payoutSpeed: 'Weekly Fridays direct deposit',
      audienceSize: 'Global creator network',
      easeOfListing: 9,
      competitionLevel: 7,
      trendingDirection: 'STABLE',
      recommendationScore: 88,
      monthlyPotential: '$800 – $4,000/mo',
      recommendedPricing: '$39.00 – $79.00',
    },
    {
      platform: 'Stan Store',
      category: 'VIDEO_CLIPS',
      payoutPercentage: 95,
      payoutSpeed: 'Daily Stripe payouts',
      audienceSize: 'TikTok & Instagram link-in-bio buyers',
      easeOfListing: 10,
      competitionLevel: 4,
      trendingDirection: 'UP',
      recommendationScore: 92,
      monthlyPotential: '$1,000 – $5,000/mo',
      recommendedPricing: '$29.00 – $49.00/bundle',
    },
    {
      platform: 'LemonSqueezy',
      category: 'DIGITAL_PRODUCT',
      payoutPercentage: 95,
      payoutSpeed: 'Bi-weekly automated ACH',
      audienceSize: 'SaaS & developer community',
      easeOfListing: 8,
      competitionLevel: 5,
      trendingDirection: 'UP',
      recommendationScore: 89,
      monthlyPotential: '$900 – $4,500/mo',
      recommendedPricing: '$49.00 – $149.00',
    },
    {
      platform: 'Etsy',
      category: 'DIGITAL_PRODUCT',
      payoutPercentage: 93.5,
      payoutSpeed: 'Next day bank transfer',
      audienceSize: 'Massive organic search volume',
      easeOfListing: 7,
      competitionLevel: 8,
      trendingDirection: 'STABLE',
      recommendationScore: 82,
      monthlyPotential: '$500 – $2,500/mo',
      recommendedPricing: '$19.00 – $39.00 (High Volume)',
    },
    {
      platform: 'Pond5 / Shutterstock',
      category: 'STOCK_FOOTAGE',
      payoutPercentage: 50,
      payoutSpeed: 'Monthly threshold ($25)',
      audienceSize: 'Film & media agencies',
      easeOfListing: 6,
      competitionLevel: 9,
      trendingDirection: 'STABLE',
      recommendationScore: 72,
      monthlyPotential: '$300 – $1,800/mo',
      recommendedPricing: '$79.00 – $199.00 per 4K asset',
    },
  ];
}

export function generateMultiPlatformListing(assetTitle: string, basePrice: number) {
  return [
    {
      platform: 'Whop',
      title: `${assetTitle} — Commercial Agency License`,
      price: basePrice,
      payoutSplit: '95% to you ($' + (basePrice * 0.95).toFixed(2) + ')',
      format: 'Instant Digital Download + Discord Role Access',
      status: 'Ready to Syndicate',
    },
    {
      platform: 'Gumroad',
      title: `${assetTitle} (Master File + SOP Guide)`,
      price: Math.round(basePrice * 0.9),
      payoutSplit: '90% to you ($' + (basePrice * 0.9 * 0.9).toFixed(2) + ')',
      format: 'Direct PDF / ZIP Delivery',
      status: 'Ready to Syndicate',
    },
    {
      platform: 'Stan Store',
      title: `${assetTitle} [1-Click Creator Bundle]`,
      price: Math.round(basePrice * 0.75),
      payoutSplit: '95% to you ($' + (basePrice * 0.75 * 0.95).toFixed(2) + ')',
      format: 'Mobile-Optimized Checkout',
      status: 'Ready to Syndicate',
    },
    {
      platform: 'Etsy',
      title: `${assetTitle} | Turnkey Commercial Template Pack`,
      price: Math.round(basePrice * 0.6),
      payoutSplit: '93.5% to you ($' + (basePrice * 0.6 * 0.935).toFixed(2) + ')',
      format: 'High-Volume Marketplace Listing',
      status: 'Ready to Syndicate',
    },
  ];
}