/* The 45 public starting points. Legacy recipes remain addressable by id.
   Copy describes the actual directive; steps are also included in the agent's task.
   Familiar everyday workflows are intentional: usefulness, not novelty, earns a place. */
'use strict';
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.RecipeCatalogCurated = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const entry = (id, category, name, description, steps) => ({ id, category, name, tagline: description, blurb: description, steps });
  return [
    entry('travel-plan', 'general', 'Plan a Trip', 'Get a day-by-day travel plan with realistic travel times, costs, and booking suggestions.', ['Research your destination and priorities.', 'Build a practical daily itinerary.', 'List costs and bookings to consider; book nothing.']),
    entry('read-this', 'general', 'Explain a Document', 'Understand a letter, policy, or agreement and find the parts that affect you.', ['Read the document and your question.', 'Explain the important terms in plain language.', 'Highlight obligations, deadlines, and unanswered questions.']),
    entry('expiry-watch', 'general', 'Find Upcoming Deadlines', 'Find renewal dates and deadlines in your documents so you can plan what to do next.', ['Read the documents you provide.', 'Extract dates, notice periods, and consequences.', 'List what needs attention and record dates for later checks.']),
    entry('find-the-catch', 'general', 'Check an Offer', 'Find hidden costs, restrictions, and trade-offs before accepting a deal.', ['Read the offer and its terms.', 'Check costs, exclusions, and important conditions.', 'Explain the trade-offs and questions to ask.']),
    entry('promises-made', 'general', 'Track My Promises', 'Find commitments you made in messages and draft follow-ups for anything still open.', ['Read the messages you choose or make available.', 'Check which promises appear unresolved.', 'Draft follow-ups and save the open list; send nothing.']),
    entry('summarize', 'general', 'Summarize Anything', 'Get the key points from text, a file, or a link without losing important qualifications.', ['Read the material you provide.', 'Identify the main points and important qualifications.', 'Write a concise summary that preserves the original meaning.']),

    entry('deep-research', 'research', 'Research a Question', 'Get a researched answer with sources, competing views, and important uncertainties.', ['Investigate the question using relevant sources.', 'Compare evidence and conflicting explanations.', 'Write a sourced answer and identify what remains uncertain.']),
    entry('fact-check', 'research', 'Check a Claim', 'Find evidence for a claim and see what is supported, disputed, or still unknown.', ['Break the claim into checkable statements.', 'Look for reliable evidence and counterevidence.', 'Explain the verdict with sources and caveats.']),
    entry('paper-summarize', 'research', 'Explain a Paper', 'Understand a research paper’s question, method, findings, and limitations.', ['Read the paper you provide.', 'Explain its methods and main findings.', 'Summarize limitations and what the results mean.']),
    entry('source-compare', 'research', 'Compare Sources', 'See where sources agree or disagree about a question and why their answers differ.', ['Find sources addressing your question.', 'Compare claims, evidence, and assumptions.', 'Explain agreements, disagreements, and gaps.']),
    entry('learning-plan', 'research', 'Learn Something New', 'Get a learning plan with practical exercises, useful resources, and clear milestones.', ['Clarify what you want to learn and your available time.', 'Research resources and order the learning stages.', 'Set a practical project and a milestone for each stage.']),
    entry('morning-brief', 'research', 'Get a Topic Brief', 'Catch up on a topic with a short, sourced summary of recent developments.', ['Find developments in your chosen time period.', 'Filter for meaningful updates.', 'Summarize what changed and link to the sources.']),

    entry('draft-reply', 'creator', 'Draft a Reply', 'Get a reply in your chosen tone, ready for you to review and send.', ['Read the message and relevant context.', 'Draft a reply in your chosen tone.', 'Leave the draft for your review; send nothing.']),
    entry('tighten-writing', 'creator', 'Improve a Draft', 'Make your writing clearer and more concise while keeping your meaning and voice.', ['Read the draft and available examples of your writing.', 'Remove clutter and improve the structure.', 'Return the revised draft with the important changes explained.']),
    entry('repurpose-queue', 'creator', 'Reuse Your Content', 'Find work worth adapting and draft a new version for another format.', ['Review your existing content.', 'Choose pieces that suit your target formats.', 'Draft a new version of the strongest candidate.']),
    entry('idea-harvest', 'creator', 'Find Ideas in Notes', 'Turn scattered notes into a short list of ideas and an outline for the strongest one.', ['Read your notes and available messages.', 'Combine related ideas and rank useful candidates.', 'Develop the strongest idea into an outline.']),
    entry('publish-checklist', 'creator', 'Check Before Publishing', 'Review a draft for errors, weak claims, and missing details before you publish it.', ['Read the draft in context.', 'Check claims, links, and presentation.', 'Return issues and suggested fixes; publish nothing.']),
    entry('stale-content-sweep', 'creator', 'Find Outdated Content', 'Find broken links and outdated claims in your published work, with suggested corrections.', ['Read the published work you choose.', 'Check links and time-sensitive claims against current sources.', 'Rank corrections by importance; report unavailable sources.']),

    entry('plan-project', 'ops', 'Plan a Project', 'Turn a goal into a practical plan with ordered tasks, dependencies, and a first step.', ['Review the goal and existing work.', 'Break the work into achievable stages.', 'Identify dependencies, risks, and the next action.']),
    entry('meeting-prep', 'ops', 'Prepare for a Meeting', 'Get a focused meeting brief with background, an agenda, and questions to ask.', ['Review the meeting and available context.', 'Identify decisions and information you need.', 'Prepare an agenda and useful questions.']),
    entry('weekly-review', 'ops', 'Review Your Week', 'See what moved forward, what got stuck, and the three priorities for next week.', ['Review your notes and any previous weekly review.', 'Identify progress, blockers, and unfinished work.', 'Choose three priorities and save the review for comparison.']),
    entry('inbox-triage-brief', 'ops', 'Sort Your Inbox', 'Turn available messages into a prioritized list of replies, decisions, and next actions.', ['Read connected messages or an export you provide.', 'Separate urgent items, decisions, and routine messages.', 'Return a prioritized action list.']),
    entry('decision-memo', 'ops', 'Compare Your Options', 'Get a clear comparison of a decision’s options, trade-offs, and remaining unknowns.', ['Review the decision and supporting material.', 'Compare options against your needs.', 'Explain the recommendation and what could change it.']),

    entry('client-proposal', 'business', 'Draft a Proposal', 'Create a client proposal covering outcomes, scope, pricing, assumptions, and next steps.', ['Review the client brief and your terms.', 'Draft scope, exclusions, pricing, and timing.', 'Flag missing information and leave the proposal for review.']),
    entry('lead-research', 'business', 'Find Potential Clients', 'Find businesses that may need your offer, with public evidence and suggested opening lines.', ['Research businesses in your chosen market.', 'Look for evidence that your offer fits their needs.', 'Rank leads and draft opening lines; contact nobody.']),
    entry('support-digest', 'business', 'Summarize Support Issues', 'Group customer support messages into recurring problems and suggested improvements.', ['Read the support messages you provide.', 'Group related problems and check available history.', 'Rank improvements and include representative customer quotes.']),
    entry('sop-write', 'business', 'Write a How-To Guide', 'Turn a process into instructions another person can follow, including checks and exceptions.', ['Review the process and intended reader.', 'Write ordered actions and what to do when a step goes wrong.', 'Flag missing details and provide a quick checklist.']),
    entry('client-onboard-kit', 'business', 'Welcome a New Client', 'Draft a welcome note, kickoff agenda, information checklist, and working agreement.', ['Review the engagement and how you work.', 'Draft the four onboarding documents.', 'Flag decisions needed before sharing; send nothing.']),

    entry('budget-build', 'money', 'Build a Budget', 'Use your income and actual spending to draft a realistic monthly budget.', ['Review the statements and income you provide.', 'Separate fixed costs from adjustable spending.', 'Suggest realistic targets and show useful trade-offs.']),
    entry('spend-audit', 'money', 'Review Your Spending', 'Group your transactions and spot recurring costs, unusual changes, and possible savings.', ['Read transactions for your chosen period.', 'Group clear items and flag uncertain categories.', 'Summarize patterns and choices that could reduce spending.']),
    entry('subscription-audit', 'money', 'Review Subscriptions', 'Find recurring charges in your statements and identify subscriptions worth reviewing.', ['Read your statement or recurring-charge list.', 'Identify subscriptions and repeated charges.', 'List costs and questions to consider before cancelling anything.']),
    entry('price-watch', 'money', 'Check a Price', 'Check a current price and compare it with saved observations; schedule it for repeat checks.', ['Check current prices from reliable sources.', 'Compare against previously recorded prices, if available.', 'Report meaningful movement or save the first observation.']),
    entry('big-purchase', 'money', 'Compare a Purchase', 'Compare three suitable products by price, long-term drawbacks, and total ownership cost.', ['Research current options that fit your priorities.', 'Compare three contenders and their full costs.', 'Recommend an option and explain trade-offs; buy nothing.']),
    entry('receipt-ledger', 'money', 'Organize Receipts', 'Turn receipt files into a traceable table with totals and flagged missing information.', ['Read each receipt and keep its original filename.', 'Extract amounts and categories; flag uncertain values.', 'Save a ledger and summarize totals and possible duplicates.']),

    entry('sheet-clean', 'data', 'Clean a Spreadsheet', 'Get consistent data with duplicates and uncertain values identified for review.', ['Inspect the file and how you plan to use it.', 'Clean clear inconsistencies and identify duplicates.', 'Return the cleaned data and explain unresolved issues.']),
    entry('data-explain', 'data', 'Understand Your Data', 'Find the main patterns in a dataset and understand what the numbers can and cannot tell you.', ['Inspect the data and its structure.', 'Analyze useful patterns and unusual values.', 'Explain findings and limitations in plain language.']),
    entry('chart-it', 'data', 'Make a Chart', 'Turn data into a readable chart that answers your question.', ['Read the data and identify the question.', 'Choose an appropriate chart and prepare the values.', 'Create the chart with clear labels and explain what it shows.']),
    entry('reconcile-lists', 'data', 'Compare Two Lists', 'Find matching records, missing entries, and conflicting values between two files.', ['Read both files and identify matching fields.', 'Compare records without guessing uncertain matches.', 'Return matches, differences, and items needing review.']),
    entry('extract-table', 'data', 'Turn Files into a Table', 'Collect chosen fields from a folder of documents into one structured table.', ['Read the documents and requested fields.', 'Extract values and record each original filename.', 'Return a table and flag missing or uncertain values.']),
    entry('survey-analyze', 'data', 'Summarize Feedback', 'Group survey answers or written feedback into themes with representative quotes.', ['Read the responses and the question asked.', 'Group themes without losing minority views.', 'Summarize patterns, examples, and limits of the sample.']),

    entry('fix-bug', 'developer', 'Fix a Bug', 'Investigate a software problem, make a focused fix, and check the result.', ['Investigate the error and relevant code.', 'Make a focused change addressing the cause.', 'Run relevant checks and report any remaining uncertainty.']),
    entry('code-review', 'developer', 'Review Code', 'Find actionable bugs and risks in code, with explanations and suggested fixes.', ['Read the code and its surrounding context.', 'Look for concrete bugs and risky behavior.', 'Prioritize findings and explain how to address them.']),
    entry('ship-feature', 'developer', 'Build a Feature', 'Add a described feature to a project and check that it works with the existing code.', ['Inspect the project and clarify the requested behavior.', 'Implement the feature using the project’s conventions.', 'Run relevant checks and explain the changes.']),
    entry('onboard-codebase', 'developer', 'Understand a Codebase', 'Get a guide to a project’s structure, main flows, and places to start working.', ['Inspect the repository and its documentation.', 'Trace the important components and execution paths.', 'Explain the structure and useful starting points.']),
    entry('dependency-audit', 'developer', 'Check Dependencies', 'Review software packages for known risks and get a prioritized upgrade plan.', ['Read the project’s dependency files.', 'Check usage, versions, and known advisories.', 'Recommend an ordered upgrade plan and validation steps.'])
  ];
});
